### ISSUE TITLE
Discord is down, bot won't start

### ISSUE THREAD

**Issue by turkunov** [perssBest/MongoDB-bot#1]
Hey, If you are still keeping the project alive, just wondering, how does the following line of code works (screenshots attached below)?

Also, your Discord link is outdated, please add a new one.

And also there is something wrong with MessageEmbed function. On sending any command I get the following error: ```(node:3617) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'client' of undefined```. 

Thanks for your answer in advance! 

Screenshot link: [https://ibb.co/r0MkrQR](url)

**Comment by er2off** [comment]
Hello. Please, provide a full error stack.

**Comment by turkunov** [comment]
> Hello. Please, provide a full error stack.

On !ping command:

```
(node:2464) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'client' of undefined
    at new MessageEmbed (/Users/test/Desktop/bots/MongoDB-bot-master/node_modules/discord.js/src/structures/MessageEmbed.js:13:60)
    at Object.execute (/Users/test/Desktop/bots/MongoDB-bot-master/commands/guild/ping.js:8:13)
    at /Users/test/Desktop/bots/MongoDB-bot-master/server.js:98:15
    at /Users/test/Desktop/bots/MongoDB-bot-master/node_modules/mongoose/lib/model.js:4826:16
    at /Users/test/Desktop/bots/MongoDB-bot-master/node_modules/mongoose/lib/model.js:4826:16
    at /Users/test/Desktop/bots/MongoDB-bot-master/node_modules/mongoose/lib/helpers/promiseOrCallback.js:24:16
    at /Users/test/Desktop/bots/MongoDB-bot-master/node_modules/mongoose/lib/model.js:4849:21
    at /Users/test/Desktop/bots/MongoDB-bot-master/node_modules/mongoose/lib/query.js:4390:11
    at /Users/test/Desktop/bots/MongoDB-bot-master/node_modules/kareem/index.js:135:16
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
(node:2464) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:2464) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by nyansterowo** [comment]
Hey. This code was written in discord.js version 11. Now in the most recent versions the **RichEmbed()** function has been removed. Instead, they made **MessageEmbed(**). Either use the old version of discord.js _(the version in which all the code was written is written in package.json)_, or rewrite for the new version.


About that line in the config. In the array, you insert the IDs of those users who will have access to all private commands.
